### ISSUE TITLE
i am not able to install pyttsx3 in visual studio code and most of other modules like pyaudio . 

### ISSUE THREAD

**Issue by surajmahendra2552** [surajmahendra2552/AUNIM#1]
i am new to programming language of python i am using visual studio code as mentioned in the title and my os is windows 8.1 pro  and my python version is 3.7.2

the following is the error:
C:\Users\SURAJ MAHENDRA\Desktop>pip install pyttsx3
Collecting pyttsx3
  Using cached pyttsx3-2.84-py3-none-any.whl (39 kB)
Collecting pyobjc>=2.4
  Using cached pyobjc-6.1-py3-none-any.whl (2.9 kB)
Collecting comtypes; "win32" in sys_platform
  Using cached comtypes-1.1.7.zip (180 kB)
Collecting pyobjc-framework-SecurityInterface==6.1
  Downloading pyobjc-framework-SecurityInterface-6.1.tar.gz (23 kB)
    ERROR: Command errored out with exit status 1:
     command: 'e:\python\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\SURAJM~1\\AppData\\Local\\Temp\\pip-install-i2qlzoqp\\pyobjc-framework-SecurityInterface\\setup.py'"'"'; __file__='"'"'C:\\Users\\SURAJM~1\\AppData\\Local\\Temp\\pip-install-i2qlzoqp\\pyobjc-framework-SecurityInterface\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\SURAJM~1\AppData\Local\Temp\pip-install-i2qlzoqp\pyobjc-framework-SecurityInterface\pip-egg-info'
         cwd: C:\Users\SURAJM~1\AppData\Local\Temp\pip-install-i2qlzoqp\pyobjc-framework-SecurityInterface\
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\SURAJM~1\AppData\Local\Temp\pip-install-i2qlzoqp\pyobjc-framework-SecurityInterface\setup.py", line
23, in <module>
        extra_link_args=["-framework", "SecurityInterface"],
      File "C:\Users\SURAJM~1\AppData\Local\Temp\pip-install-i2qlzoqp\pyobjc-framework-SecurityInterface\pyobjc_setup.py", line 408, in Extension
        os_level = get_os_level()
      File "C:\Users\SURAJM~1\AppData\Local\Temp\pip-install-i2qlzoqp\pyobjc-framework-SecurityInterface\pyobjc_setup.py", line 218, in get_os_level
        pl = plistlib.readPlist("/System/Library/CoreServices/SystemVersion.plist")
      File "e:\python\lib\plistlib.py", line 99, in readPlist
        with _maybe_open(pathOrFile, 'rb') as fp:
      File "e:\python\lib\contextlib.py", line 112, in __enter__
        return next(self.gen)
      File "e:\python\lib\plistlib.py", line 82, in _maybe_open
        with open(pathOrFile, mode) as fp:
    FileNotFoundError: [Errno 2] No such file or directory: '/System/Library/CoreServices/SystemVersion.plist'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

i have tried many times by changing the directory and even turned to pycharm but to no avail.
i just cant understand whats the problem. can anyone help me and please explain me layman's language as i am new.
thanking you sir/madam.

**Comment by SwayamTakkamore** [comment]
I also have the same issue.

**Comment by KotonBads** [comment]
try pip install pyttsx3==2.71

**Comment by sushantkhara** [comment]
I had issue with installing the pyttsx3 library,its working for me now.Thanks @KotonBads

**Comment by SwayamTakkamore** [comment]
try this,
Enter all step by step---

1. pip install pipwin
2. pipwin install pyttsx3
3. pipwin install pyaudio

**Comment by jatin3311** [comment]
pip install pyttsx3

Run the above given code in visual studio code terminal
